[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
biscuit = "AguvXyhZXA9WMXfezVHCnz9rjGDPRrDY6FdMcmgSaaKN"

[programs.devnet]
biscuit = "AguvXyhZXA9WMXfezVHCnz9rjGDPRrDY6FdMcmgSaaKN"

[registry]
url = ""

[provider]
cluster = "devnet"
wallet = "/home/mykola_admin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"  
program = "dumps/metaplex_token_metadata_program.so"

[[test.genesis]]
address = "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc"  
program = "dumps/whirlpool_program.so"

[[test.validator.account]]
address = "2LecshUwdy9xi7meFgHtFJQNSKk4KdTrcpvaB56dP2NQ"
filename = "dumps/whirlpool_config.json"

[[test.validator.account]]
address = "BGnhGXT9CCt5WYS23zg9sqsAT2MGXkq7VSwch9pML82W"
filename = "dumps/wpool_fee_tier_128.json"

